### ISSUE TITLE
NATS server process not killed on all platforms

### ISSUE THREAD

**Issue by jDzames** [YunaBraska/nats-streaming-server#1]
Hello,

we stumbled upon problem with stopping embedded nats process. `Nats.stop()` is called, but seems it doesn't work on all platforms, or better to say "linux distributions". It works fine on Manjaro linux, but it consistently **fails to kill nats process on Ubuntu** linux. 

We suspect that problem might be that `process.destroy()` is called on some nats server parent process (can it be terminal running it?) and this leads to different behavior on different OSes.

@kravemir is looking into it as well, as he is on Ubuntu. He had some ideas, so he can post them here or raise PR if he gets to try it...

**Comment by YunaBraska** [comment]
Hello again :)

supporting linux distributions is always difficult. Can you try to use the timeout parameter? E.g.`Nats.stop(10000)`. The `Terminal` is just a Wrapper of the process which takes care of executing commands, it shouldn't have any separate thread. I will try to reproduce it. I am also considering to look for a proper library which handles processes better... Of curse a PR would be awesome, debugging OS behaviour is always hard :D Lets install Ubuntu somewhere...

**Comment by jDzames** [comment]
> Can you try to use the timeout parameter? E.g.Nats.stop(10000).

I don't think this would change anything. This is what exactly people reported:
1. They run tests for the first time (nats is started before tests, on spring startup)
2. Tests pass fine (nats _should be_ killed after all tests are done, on spring shutdown, `stop` method is indeed executed)
3. After few minutes they try to run tests again, but old nats server is still running (it is not that it just dies slowly, it is not dying at all), so spring startup crashes when trying to start new nats server (for currently run tests)

From discussion with colleagues and after some googling I think it will really be problem with `process.destroy()` not killing sub-processes (that is nats server in this case)... Seems there is a lot of written about this across forums and bug tickets, but I haven't found reasonable solution. :disappointed: 

Maybe just try different way of creating or destroying process on linux distributions? There was idea to use `exec` for starting server, this could replace terminal with server process or try killing process e.g. like this  https://stackoverflow.com/a/2173421 ?

**Comment by YunaBraska** [comment]
thx for the research, I will have a look into it. 👍
About the timeout thingy, This fixed at least my GitHub Ubuntu pipeline some weeks ago. 
But anyway I will try to exchange the `process.destroy()` with a kill thingy. First for linux at least.

To unblock you while the fix is ongoing, you could handle things by your self like:
```
if(SystemUtil.getOsType() == LINUX) {
  new Terminal().execute("command)
}
```

**Comment by YunaBraska** [comment]
Haha Github auto closed the issue :D can you test the version `0.20.10`? I tested it on ubuntu at least on the pipeline with this test: https://github.com/YunaBraska/nats-streaming-server/blob/4dae8c7dd65646981e2a634db69c5e5d0f884d2e/src/test/java/berlin/yuna/natsserver/logic/NatsStreamingComponentTest.java#L112 hope this solved the issue. Also you can now call a method `getPid()` to get the actual PID :) The current solution calls nats to shutdown by the `--signal stop` parameter

**Comment by jDzames** [comment]
Thanks, going to test.

And btw, not related to this (but I wouldn't open separate "issue" for that), I noticed there is now way to set random port to server now. It would be useful to be able to easily get it from `NatsStreaming` (as we would use it in app to connect to server). I see it is possible to get it through configs map, but more direct way would be preferred. 
My reasoning would be that other options are either as you set them or default ones. Random port is neither and you usually need to know its value it in the app.
(It can be either simple "getter" or create separate method to generate + set + return port value... Whatever you prefer.)

**Comment by kravemir** [comment]
@YunaBraska thank you for the fix! I can confirm, the fix worked.
